package contractgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"
)

type document struct {
	Defs map[string]schema `json:"$defs"`
}

type schema struct {
	Type       string            `json:"type"`
	Ref        string            `json:"$ref"`
	Properties map[string]schema `json:"properties"`
	Required   []string          `json:"required"`
	Items      *schema           `json:"items"`
	Const      any               `json:"const"`
}

// Generate converts the deliberately small Phase 1 JSON-Schema subset into
// deterministic Go structs. JSON Schema remains the contract source of truth.
func Generate(raw []byte, packageName string) ([]byte, error) {
	var doc document
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse schema: %w", err)
	}
	if len(doc.Defs) == 0 {
		return nil, fmt.Errorf("schema has no $defs")
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by cmd/contractgen; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "package %s\n\n", packageName)

	names := sortedKeys(doc.Defs)
	for _, name := range names {
		def := doc.Defs[name]
		if def.Type != "object" {
			continue
		}
		required := make(map[string]bool, len(def.Required))
		for _, field := range def.Required {
			required[field] = true
		}
		fmt.Fprintf(&out, "type %s struct {\n", goName(name))
		for _, jsonName := range sortedKeys(def.Properties) {
			prop := def.Properties[jsonName]
			goType, err := typeFor(prop)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, jsonName, err)
			}
			tag := jsonName
			if !required[jsonName] {
				if prop.Ref != "" {
					goType = "*" + goType
				}
				tag += ",omitempty"
			}
			fmt.Fprintf(&out, "\t%s %s `json:\"%s\"`\n", goName(jsonName), goType, tag)
		}
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
	}

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, out.String())
	}
	return formatted, nil
}

func typeFor(s schema) (string, error) {
	if s.Ref != "" {
		const prefix = "#/$defs/"
		if !strings.HasPrefix(s.Ref, prefix) {
			return "", fmt.Errorf("unsupported ref %q", s.Ref)
		}
		return goName(strings.TrimPrefix(s.Ref, prefix)), nil
	}
	if s.Const != nil {
		return "string", nil
	}
	switch s.Type {
	case "string":
		return "string", nil
	case "boolean":
		return "bool", nil
	case "integer":
		return "int64", nil
	case "array":
		if s.Items == nil {
			return "", fmt.Errorf("array without items")
		}
		item, err := typeFor(*s.Items)
		if err != nil {
			return "", err
		}
		return "[]" + item, nil
	case "object":
		return "map[string]any", nil
	default:
		return "", fmt.Errorf("unsupported type %q", s.Type)
	}
}

func goName(s string) string {
	if s == "" {
		return "Field"
	}
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '_' || r == '-' || r == '.' || r == ' ' {
			upper = true
			continue
		}
		if upper {
			r = unicode.ToUpper(r)
			upper = false
		}
		b.WriteRune(r)
	}
	return b.String()
}

func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
