// Code generated by cmd/contractgen; DO NOT EDIT.

package v1

type CapabilityDescriptor struct {
	Actions      []string `json:"actions"`
	CapabilityId string   `json:"capabilityId"`
	Version      string   `json:"version"`
}

type CapabilityRequest struct {
	Action      string         `json:"action"`
	Capability  string         `json:"capability"`
	Deadline    string         `json:"deadline"`
	MessageType string         `json:"messageType"`
	Params      map[string]any `json:"params"`
	RequestId   string         `json:"requestId"`
	Timestamp   string         `json:"timestamp"`
	WorkspaceId string         `json:"workspaceId,omitempty"`
}

type CapabilityResponse struct {
	Error       *ProtocolError `json:"error,omitempty"`
	MessageType string         `json:"messageType"`
	RequestId   string         `json:"requestId"`
	Result      map[string]any `json:"result,omitempty"`
	Timestamp   string         `json:"timestamp"`
}

type ClientHello struct {
	Arch               string                 `json:"arch"`
	Capabilities       []CapabilityDescriptor `json:"capabilities"`
	ChallengeSignature string                 `json:"challengeSignature"`
	MachineId          string                 `json:"machineId"`
	MessageType        string                 `json:"messageType"`
	NodeVersion        string                 `json:"nodeVersion"`
	Os                 string                 `json:"os"`
	ProtocolVersions   []string               `json:"protocolVersions"`
	Timestamp          string                 `json:"timestamp"`
}

type ConnectionClose struct {
	Code        string `json:"code"`
	MessageType string `json:"messageType"`
	Reason      string `json:"reason"`
	Timestamp   string `json:"timestamp"`
}

type Heartbeat struct {
	MessageType string `json:"messageType"`
	Sequence    int64  `json:"sequence"`
	Status      string `json:"status"`
	Timestamp   string `json:"timestamp"`
}

type Machine struct {
	Arch         string                 `json:"arch"`
	Capabilities []CapabilityDescriptor `json:"capabilities,omitempty"`
	DisplayName  string                 `json:"displayName"`
	Generation   int64                  `json:"generation"`
	LastSeenAt   string                 `json:"lastSeenAt,omitempty"`
	MachineId    string                 `json:"machineId"`
	NodeVersion  string                 `json:"nodeVersion"`
	Online       bool                   `json:"online"`
	Os           string                 `json:"os"`
	Status       string                 `json:"status"`
}

type NodeReady struct {
	MessageType string `json:"messageType"`
	Status      string `json:"status"`
	Timestamp   string `json:"timestamp"`
}

type ProtocolError struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
}

type ServerHello struct {
	Challenge        string   `json:"challenge"`
	HubFingerprint   string   `json:"hubFingerprint"`
	HubPublicKey     string   `json:"hubPublicKey"`
	MessageType      string   `json:"messageType"`
	ProtocolVersions []string `json:"protocolVersions"`
	ServerSignature  string   `json:"serverSignature"`
	Timestamp        string   `json:"timestamp"`
}

type SessionEstablished struct {
	ConnectionId     string `json:"connectionId"`
	Generation       int64  `json:"generation"`
	HeartbeatSeconds int64  `json:"heartbeatSeconds"`
	MessageType      string `json:"messageType"`
	ProtocolVersion  string `json:"protocolVersion"`
	Timestamp        string `json:"timestamp"`
}

type WorkspaceSummary struct {
	DisplayName string `json:"displayName"`
	Enabled     bool   `json:"enabled"`
	Revision    int64  `json:"revision"`
	WorkspaceId string `json:"workspaceId"`
}
